Traceback (most recent call last):
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import seaborn as sns

sns.lineplot( x = 'Year', y = Y, data = dftime, hue = "User_role2")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_16821/3858848429.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mseaborn[0m [0;32mas[0m [0msns[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0msns[0m[0;34m.[0m[0mlineplot[0m[0;34m([0m [0mx[0m [0;34m=[0m [0;34m'Year'[0m[0;34m,[0m [0my[0m [0;34m=[0m [0mY[0m[0;34m,[0m [0mdata[0m [0;34m=[0m [0mdftime[0m[0;34m,[0m [0mhue[0m [0;34m=[0m [0;34m"User_role2"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/.local/lib/python3.9/site-packages/seaborn/relational.py[0m in [0;36mlineplot[0;34m(x, y, hue, size, style, data, palette, hue_order, hue_norm, sizes, size_order, size_norm, dashes, markers, style_order, units, estimator, ci, n_boot, seed, sort, err_style, err_kws, legend, ax, **kwargs)[0m
[1;32m   1118[0m              legend="brief", ax=None, **kwargs):
[1;32m   1119[0m [0;34m[0m[0m
[0;32m-> 1120[0;31m     p = _LinePlotter(
[0m[1;32m   1121[0m         [0mx[0m[0;34m=[0m[0mx[0m[0;34m,[0m [0my[0m[0;34m=[0m[0my[0m[0;34m,[0m [0mhue[0m[0;34m=[0m[0mhue[0m[0;34m,[0m [0msize[0m[0;34m=[0m[0msize[0m[0;34m,[0m [0mstyle[0m[0;34m=[0m[0mstyle[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdata[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1122[0m         [0mpalette[0m[0;34m=[0m[0mpalette[0m[0;34m,[0m [0mhue_order[0m[0;34m=[0m[0mhue_order[0m[0;34m,[0m [0mhue_norm[0m[0;34m=[0m[0mhue_norm[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.9/site-packages/seaborn/relational.py[0m in [0;36m__init__[0;34m(self, x, y, hue, size, style, data, palette, hue_order, hue_norm, sizes, size_order, size_norm, dashes, markers, style_order, units, estimator, ci, n_boot, seed, sort, err_style, err_kws, legend)[0m
[1;32m    692[0m                  sort=True, err_style=None, err_kws=None, legend=None):
[1;32m    693[0m [0;34m[0m[0m
[0;32m--> 694[0;31m         plot_data = self.establish_variables(
[0m[1;32m    695[0m             [0mx[0m[0;34m,[0m [0my[0m[0;34m,[0m [0mhue[0m[0;34m,[0m [0msize[0m[0;34m,[0m [0mstyle[0m[0;34m,[0m [0munits[0m[0;34m,[0m [0mdata[0m[0;34m[0m[0;34m[0m[0m
[1;32m    696[0m         )

[0;32m~/.local/lib/python3.9/site-packages/seaborn/relational.py[0m in [0;36mestablish_variables[0;34m(self, x, y, hue, size, style, units, data)[0m
[1;32m    135[0m                 [0;32mif[0m [0misinstance[0m[0;34m([0m[0mvar[0m[0;34m,[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    136[0m                     [0merr[0m [0;34m=[0m [0;34m"Could not interpret input '{}'"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mvar[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 137[0;31m                     [0;32mraise[0m [0mValueError[0m[0;34m([0m[0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    138[0m [0;34m[0m[0m
[1;32m    139[0m             [0;31m# Extract variable names[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Could not interpret input 'User_role2'
ValueError: Could not interpret input 'User_role2'

